README.md
Fixes `vue-router` link in readme to point to correct path.
Just starting to try it out a bit. Easy to get going, great work! 👍
=> Fix vue-router link in readme

src/index.js
Exposing the wrapper.emitted() method so that Vue custom events can be inspected.
=> Expose wrapper.emitted

src/index.js, tests/__tests__/components/Button.vue, tests/__tests__/simple-button.js
Hello @dfcook really happy you've made this library. 
A little problem I've found is that is that you can't use the `getQueriesForElement` methods on the returned element e.g.
```vue
// SimpleButton.vue
<template>
<button :class="typeClass" @click="clicked">{{ text }}</button>
</template>
```
```js
// button-test.js
test('renders button with text', () => {
const buttonText = "Click me; I'm sick"
const { getByText } = render(SimpleButton, {
props: { text: buttonText, clicked: () => true }
})
getByText(buttonText)
})
```
As it stands this fails because getByText is querying within the returned element. This scenario works in `react-testing-library` because it wraps the rendered component in a div. 
This PR essentially wraps the `vue-test-utils` wrapper in a `div` and passes that to the …
=> Wraps rendered component in a div

README.md, package.json, src/index.js, tests/__tests__/components/Button.vue, tests/__tests__/components/Form.vue, tests/__tests__/fetch.js, tests/__tests__/integration-with-stubs.js, tests/__tests__/simple-button.js, yarn.lock
Allow all supported options to be passed to vue-test-utils mount function. Replaces #12 , hence including test from that PR in here.
=> Support all mount options in vue-test-utils

README.md
Hi! I've found some small typos in the README, and also I believe the link pointing to `wait` example wasn't the right one.
Thanks!
=> Small tweaks on README

tests/__tests__/components/Button.vue, tests/__tests__/router/programmatic-routing/components/Home.vue, tests/__tests__/simple-button.js
...instead of callback props, which are way more common in React world.
I also noticed a linting issue, so I ran `npm run lint:fix` and committed the difference.
Thanks for your work!
This closes #24
=> Make button test use event emitters

.gitignore, README.md, cleanup-after-each.js, jest.config.js, package-lock.json, package.json, tests/__tests__/debug.js, tests/__tests__/end-to-end.js, tests/__tests__/fetch.js, tests/__tests__/form.js, tests/__tests__/integration-with-stubs.js, tests/__tests__/number-display.js, tests/__tests__/router/programmatic-routing/index.js, tests/__tests__/simple-button.js, tests/__tests__/stopwatch.js, tests/__tests__/validate-plugin.js, tests/__tests__/vue-router.js, tests/__tests__/vuex.js
1. Add cleanup-after-each in same manner as react-testing-library
2. Add jest module name mapper so tests can import the scoped package
3. Update package name in readme
=> #27 - Provide cleanup-after-each

README.md
Several things could change, thus I decided to create a PR so we can discuss them easily :)
Again, this is totally a proposal! Just felt that having an open PR would simplify things!
This PR closes #33
=> Remove duplication from README and official docs

package-lock.json, package.json, src/vue-testing-library.js, tests/__tests__/components/Login.vue, tests/__tests__/form.js
Add update method to handle form updates without having to call updateState
=> Add update method for model updates

src/vue-testing-library.js
For https://github.com/testing-library/vue-testing-library/issues/47. Allow the returning of an object from the callback of the third parameter of the render function in order to get additional options that may need to use the vue instance once it is created, before the `mount` internally using `@vue/test-utils`.
=> Return object from callback.

src/vue-testing-library.js, tests/__tests__/components/Form.vue, tests/__tests__/components/Select.vue, tests/__tests__/form.js, tests/__tests__/select.js
AFAIK, `checkbox` and `radio` elements use a `checked` property to express that they've been selected, which is set to `true`. So there's no need to pass a `value` argument.
Same thing with `<option>` elements. There was an issue with `this` (due to copy&paste, I guess! 😇), so I also improved naming a bit. 
I also improved tests a bit, to demonstrate that the updated element in each case is properly being checked.
=> Fix radio, checkbox and select

package-lock.json, tests/__tests__/validate-plugin.js
Travis was failing due to `VeeValidate` tweaking its warning texts, so I just made the text query more resilient.
=> Fix validation

tests/__tests__/components/Card.vue, tests/__tests__/slots.js
For #68. Adds a simple `Card` component and test that asserts slot and scopedSlot content.
=> #68 add example for slots and scoped slots

src/vue-testing-library.js, tests/__tests__/components/Button.vue, tests/__tests__/fire-event.js
As suggested in https://github.com/testing-library/user-event/pull/153, VTL mutating `fireEvent` from DOM Testing Library is giving us a hard time trying to make `user-event` usable in VTL. Also, I'd say that mutating an imported object isn't the safest strategy.
I've also added a bunch of tests for the "new" `fireEvent`.
~This is not a breaking change.~ Actually, it is. `fireEvent()` now returns a Promise, and it didn't.
=> Use and expose a local copy of fireEvent

package-lock.json, package.json, src/vue-testing-library.js, tests/__tests__/components/FunctionalSFC.vue, tests/__tests__/functional.js
Addresses #41 
1. Adds example of functional rendering using a render function.
2. Adds support for functional SFC's without a component definition by checking the isVueInstance property of the wrapper before calling destroy.
=> 41 functional rendering

tests/__tests__/within.js
`within()` might be useful sometimes, and I couldn't find any example using it.
=> Add within() test example

README.md, package-lock.json, package.json
Closes #84 
Following the strategy outlined here https://github.com/testing-library/react-testing-library/pull/437, I'm adding [VTL types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/testing-library__vue) as a dependency.
This means that people installing `@testing-library/vue` would get `@types/testing-library__vue` installed automatically. So from the developers point of view, it's as though the type definitions shipped with the package directly. (adapted from [here](https://blog.johnnyreilly.com/2019/08/symbiotic-definitely-typed.html)).
=> Add Vue Testing Library types from DefinitelyTyped

README.md, src/__tests__/__snapshots__/axios-mock.js.snap, src/__tests__/auto-cleanup-skip.js, src/__tests__/auto-cleanup.js, src/__tests__/axios-mock.js, src/__tests__/components/Translations.vue, src/__tests__/debug.js, src/__tests__/disappearance.js, src/__tests__/form.js, src/__tests__/functional.js, src/__tests__/select.js, src/__tests__/simple-button.js, src/__tests__/stopwatch.js, src/__tests__/update-props.js, src/__tests__/vue-i18n.js
=> docs: improve wording and structure

src/__tests__/components/Collapsible.vue, src/__tests__/visibility.js
=> Collapsible element visibility example

package-lock.json, package.json, src/__tests__/components/Vuetify.vue, src/__tests__/render.js, src/__tests__/vuetify.js, src/vue-testing-library.js
This PR aims to fix several issues when trying to query content outside of the regular DOM node tree (portals, modals, etc). It tries to mirror React Testing Library behavior.
I also added a test based on Vuetify, because (1) it is related to the introduced changes and (2) Vuetify is widely-used and comes with its own nuances.
This is a **breaking change** since `container` and `baseElement` changed their meaning.
This PR closes #98
=> Bound queries to the base element

src/__tests__/vuetify.js
As discussed in this thread https://github.com/testing-library/vue-testing-library/issues/98 there are some extra steps required to make Vuetify work with the VTL render.
This PR will add a custom render wrapper function to the test as an easy example for any future readers.
=> Add custom Vuetify render wrapper to Vuetify test

README.md
We have a test example for Vuetify, which could be shown in the list of examples for popular libraries.
=> Add Vuetify test to "popular libraries" examples

jest.config.js, src/__tests__/components/Directive.vue, src/__tests__/directive.js, src/__tests__/directives/uppercase-directive.js
This PR aims to add an easy-to-understand Vuejs directive example and how to test it.
fixes #108
=> Directive test example

.github/ISSUE_TEMPLATE/bug_report.md, .prettierrc.js, README.md, package-lock.json, package.json, src/__tests__/auto-cleanup.js, src/__tests__/axios-mock.js, src/__tests__/directive.js, src/__tests__/disappearance.js, src/__tests__/form.js, src/__tests__/render.js, src/__tests__/select.js, src/__tests__/simple-button.js, src/__tests__/slots.js, src/__tests__/stopwatch.js, src/__tests__/update-props.js, src/__tests__/validate-plugin.js, src/__tests__/visibility.js, src/__tests__/vue-i18n.js, src/__tests__/vue-router.js, src/__tests__/vueI18n.js, src/__tests__/vuetify.js, src/__tests__/vuex.js
I also updated Prettier config to match [RTL's](https://github.com/testing-library/react-testing-library/blob/master/.prettierrc)
=> feat(screen): add screen export from DTL + Update deps

src/__tests__/components/Vuetify.vue, src/__tests__/vuetify.js
I suggest an alternative approach to the problem to preserve things like `props, propsData, updateProps` that are applied to the root node only.
=> Alternative approach for integration with Vuetify

src/__tests__/vue-router-mocha.js, src/vue-testing-library.js
This code fixes [issue](https://github.com/testing-library/vue-testing-library/issues/119).
=> fix(#119): allow vue-router creation through routes param from both jest and mocha

src/__tests__/components/Vuetify.vue, src/__tests__/vuetify.js
In #123 I introduced a different approach to integrate with Vuetify. Unfortunately `setAttribute` [always returns undefined](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute), so `container` eventually was undefined. 
In my own project this lead to bespoken `Unable to localte target [data-app]` warnings when rendering certain vuetify components, such as `v-menu` or `v-dialog`. In this example that went unnoticed, because the example component itself was wrapped within `v-app`.
I fixed that and added tests for it.
_A sidenote: In my own project, adding the container to the body(`document.body.appendChild(root)`) lead to side-effects when interacting with `v-menu`. It seemed like the component was leaking between tests. Even with Jest running as `--runInBand`. However …
=> Fix vuetify example

README.md, package-lock.json, package.json, src/__tests__/components/Vuetify.vue, src/__tests__/vuetify.js, src/vue-testing-library.js
Upgrades version of `@vue/test-utils` to `^1.0.1`.
- Replace `attachToDocument` with `attachTo` and mirror default behaviour
- Remove guard for `wrapper.destroy` as destroy must always be called now is using `attachTo` see `@vue/test-utils` docs [here](https://vue-test-utils.vuejs.org/api/options.html#attachto).
- ~Adds `config.showDeprecationWarnings = false` as `isVueInstance` is still used internally by `@vue/test-utils` and gives warnings.~
closes #138
=> fix: update VTU to v1, update types

.github/ISSUE_TEMPLATE/bug_report.md, README.md
=> Link to new Discord and several other improvements on Readme

.travis.yml
Also, set node 15 as a fixed version so this won't fail unexpectedly again in the future.
Also, mark `beta` as a branch to run CI against.
=> test: fix CI by installing latest npm version on each run

README.md
Hey folks! I'm just starting out with `@testing-library/vue` and since the README said `You may also be interested in installing jest-dom` I tried installing it, only to then find out it was moved to `@testing-library/jest-dom`, so I had to install the other one.
Perhaps this little change could save other people some time - I'd be happy if you considered accepting it.
Thanks for reading 😊
=> Use `@testing-library/jest-dom` in README.md

src/__tests__/update-props.js, src/vue-testing-library.js
I just discovered a bug in one of my projects with the `updateProps` function returned from `render`. Whenever `updateProps` is called multiple times, several errors are logged in the console and Jest is prevented from finishing its test run. This is a huge bug for obvious reasons. Anyone can reproduce this error by grabbing the (currently) latest version of VTL and making multiple `await`ed calls to `updateProps` in a test for a Vue component.
The logged errors seem to be related to asynchronicity. I think that since the `Promise` returned from `updateProps` is different from the one returned from `waitFor`, everything gets thrown out of balance when the developer tries to run tests with multiple `updateProps` calls.
The fix I'm proposing simply returns the `Promise` obtained from …
=> Fix updateProps Function

types/index.d.ts, types/test.ts
Port of testing-library/react-testing-library#833
=> fix(types): allow all elements

src/__tests__/components/Form.vue, src/__tests__/form.js, src/vue-testing-library.js
- switched to use change event if lazy modifier is found on element
- updated form unit test to test lazy input and textarea
=> Make fireEvent.update work with lazy modifier

types/index.d.ts
Following https://github.com/testing-library/react-testing-library/pull/821, this PR will resolve the issue for this library also.
This was raised in a comment in https://github.com/testing-library/react-testing-library/issues/694.
=> fix: import pretty-format from testing-library/dom

src/__tests__/validate-plugin.js, src/__tests__/vue-i18n.js, types/index.d.ts
I noticed these build errors in #182 but realized they aren't the fault of that PR. It seems like some ESLint dependency update has introduced new failing rules, so I've fixed them.
=> chore: fix updated ESLint rules

src/__tests__/user-event.js
`userEvent` is entirely synchronous (except for `type`'s `delay` option which isn't used), so we should use it without `await` and encourage users to do the same.
=> test: remove await from userEvent usage

package.json, src/__tests__/components/Router/App.vue, src/__tests__/components/Router/LocationDisplay.vue, src/__tests__/components/Router/NoMatch.vue, src/__tests__/vue-router-mocha.js, src/__tests__/vue-router.js, src/index.js
[Vue Router](https://github.com/vuejs/vue-router-next) is out of beta and looks like we already provide basic support.
=> feat: Reenable Vue Router for Vue 3

src/__tests__/rerender.js, src/index.js
=> fix(rerender): Do not mount component again on rerender

package.json, src/__tests__/plugins.js, src/index.js
TL;DR: `lodash.merge` does not merge arrays, so plugins and vuex/router were overriding each other and other plugins.
=> fix(plugins): allow setting vuex/router and custom plugins

src/__tests__/vue-router.js
First of all, thank you for all the test examples. It really helped me to set up the test environment on my project.
I found that this test uses `queryBy*` to query the element with `location-display` testid
As it's mentioned in this [link](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-query-variants-for-anything-except-checking-for-non-existence), using `getBy*` query might fit better for this test I think.
=> replaced queryByTestId with getByTestId in the vue-router test

.eslintrc.js
This rule is currently breaking for some reason in our tests:
https://github.com/testing-library/vue-testing-library/runs/2226695857?check_suite_focus=true
=> chore(lint): disable unbound-method rule

src/__tests__/vuex.js, src/render.js, types/index.d.ts, types/test.ts
As currently written, the `store` property passed to the `render` function must be `StoreOptions`, which is a plain Javascript object passed to `new Vuex.Store()` in the render function.
This is great for simple components and should definitely still be a supported option. However, it would be really useful for us to be able to pass a complex, instantiated Vuex store (generated by our common test helpers) as well.
This PR accomplishes this behavior by checking if the passed `store` is an `instance of Vuex.Store` and skipping the `new Vuex.Store()` call in that case.
If this seems reasonable, I can also update the API documentation in the other repository 😄 . Thanks for your time & consideration!
=> feat: allow passing instantiated Vuex store

src/__tests__/vue-router.js, src/render.js, types/index.d.ts, types/test.ts
This PR supersedes #238 and is similar to #232. If `routes` is an instantiated Vue Router, it will be used instead of creating a new Vue Router. This allows developers to use `abstract` mode to avoid the issue described in #210.
Fixes #210 
See also docs upates here: https://github.com/testing-library/testing-library-docs/pull/875
=> feat: allow passing instantiated Vue Router

types/index.d.ts
I'm not sure if there's a more clever way to do this, but this should work. The linked issue has a reproduction example.
Fixes #240
=> fix: support TypeScript v3

.eslintrc.js, package.json, src/__tests__/auto-cleanup.js, src/__tests__/form-user-event.js, src/__tests__/select-user-event.js, src/__tests__/vuetify.js, src/__tests__/within.js, src/fire-event.js, types/test.ts
Rather than upgrade to kcd-scripts 11 and use Jest 27 which will require some updates to vue-jest, we can just upgrade to kcd-scripts 10 for now.
=> chore: upgrade to kcd-scripts 10

.github/workflows/validate.yml, README.md, src/fire-event.js
as Git announced that main  should be your primary branch, I'm renaming all master references tp main
**What**:
**Why**:
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)
=> chore: rename proj. from master to main

package.json
Only updates engines, as CI has already been updated.
=> feat: drop Node 10 support

types/index.d.ts, types/test.ts
Closes https://github.com/testing-library/vue-testing-library/issues/187
I'm not entirely sure this is the best way to fix the issue, but I want to get the ball rolling.
=> fix(types): Remove Router and Vuex dependency from types

src/__tests__/vuex.js
=> chore: globally .use(Vuex) when using instantiated store

types/index.d.ts
=> fix(types): Pass Store type to RenderOptions/render function

package.json
I expect nothing will break
cc @afontcu
=> chore: pin `@vue/test-utils` version to `^2.0.0`

README.md
Fix wrong vue-i18n example link
=> docs: Fix outdated vue-i18n example link

src/__tests__/form.js, src/__tests__/user-event.js, src/render.js, types/index.d.ts, types/index.test-d.ts
Vue test utils allow to pass event name  into `emitted()` to receive array of calls
`emitted().foo` can be written as `emitted('foo')`
You can see it [here](https://test-utils.vuejs.org/api/#emitted)
=> fix: add missed optional prop for emmited function

src/__tests__/auto-cleanup-vitest-globals.js, src/__tests__/auto-cleanup-vitest.js, src/index.js
This partially addresses https://github.com/testing-library/vue-testing-library/issues/296 and will make more sense after docs are updated
=> Throw error when running vitest with no afterEach global and no VTL_SKIP_AUTO_CLEANUP

package.json
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>
Close #272.
Refer to the [README](https://www.npmjs.com/package/@vue/compiler-sfc), after `v3.2.13`, the `@vue/compiler-sfc` can be optional because it has already been included in the `vue` package.
So I mark this peer dependency as optional.
=> chore: optional compiler-sfc

src/__tests__/render.js, src/render.js
=> fix: check wrapper element to fix #311
